"""initial_schema

Revision ID: 4463cdaca3c1
Revises: 
Create Date: 2026-03-04 12:56:25.597176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4463cdaca3c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('available_home', sa.Boolean(), nullable=False),
    sa.Column('available_gym', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ml_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('session_ids', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%S', 'now'))"), nullable=False),
    sa.Column('processed_at', sa.String(), nullable=True),
    sa.CheckConstraint("job_type IN ('FINE_TUNE', 'PREDICT')", name='ck_ml_job_type'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'done', 'failed')", name='ck_ml_job_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movement_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('muscle_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('body_region', sa.String(), nullable=False),
    sa.Column('is_push', sa.Boolean(), nullable=False),
    sa.Column('is_pull', sa.Boolean(), nullable=False),
    sa.Column('stretch_mediated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('readiness_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_date', sa.String(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=False),
    sa.Column('stress_level', sa.Integer(), nullable=False),
    sa.Column('hrv_score', sa.Float(), nullable=True),
    sa.Column('recovery_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bodyweight_kg', sa.Float(), nullable=True),
    sa.Column('initial_weight_coefficients', sa.Text(), nullable=True),
    sa.Column('available_equipment', sa.Text(), nullable=True),
    sa.Column('training_split', sa.Enum('ppl', 'upper_lower', 'full_body', 'custom', name='trainingsplit'), nullable=False),
    sa.Column('training_days_per_week', sa.Integer(), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%S', 'now'))"), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.CheckConstraint("training_split IN ('ppl', 'upper_lower', 'full_body', 'custom')", name='ck_user_profile_training_split'),
    sa.CheckConstraint('training_days_per_week >= 3 AND training_days_per_week <= 6', name='ck_user_profile_training_days'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('methodology', sa.String(), nullable=True),
    sa.Column('planned_exercises', sa.Text(), nullable=True),
    sa.Column('split_day_label', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%S', 'now'))"), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'active', 'completed')", name='ck_workout_session_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primary_muscle_id', sa.Integer(), nullable=False),
    sa.Column('movement_pattern_id', sa.Integer(), nullable=False),
    sa.Column('secondary_muscle_ids', sa.Text(), nullable=False),
    sa.Column('is_compound', sa.Boolean(), nullable=False),
    sa.Column('stretch_mediated', sa.Boolean(), nullable=False),
    sa.Column('equipment_type', sa.Enum('barbell', 'dumbbell', 'machine', 'cable', 'bodyweight', 'resistance_band', 'pullup_bar', 'dips_bar', name='equipmenttype'), nullable=False),
    sa.CheckConstraint("equipment_type IN ('barbell', 'dumbbell', 'machine', 'cable', 'bodyweight', 'resistance_band', 'pullup_bar', 'dips_bar')", name='ck_exercise_equipment_type'),
    sa.ForeignKeyConstraint(['movement_pattern_id'], ['movement_patterns.id'], ),
    sa.ForeignKeyConstraint(['primary_muscle_id'], ['muscle_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rpe_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('predicted_rpe', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%S', 'now'))"), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('rir', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%S', 'now'))"), nullable=False),
    sa.CheckConstraint('rir IS NULL OR (rir >= 0 AND rir <= 4)', name='ck_workout_set_rir_range'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'exercise_id', 'set_number', name='uq_workout_set')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_sets')
    op.drop_table('rpe_predictions')
    op.drop_table('exercises')
    op.drop_table('workout_sessions')
    op.drop_table('user_profiles')
    op.drop_table('readiness_logs')
    op.drop_table('muscle_groups')
    op.drop_table('movement_patterns')
    op.drop_table('ml_jobs')
    op.drop_table('equipment')
    # ### end Alembic commands ###
